# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/sistema_pwmModule.srcs/sources_1/bd/sistema_pwm/ip/sistema_pwm_rst_ps7_0_100M_0/sistema_pwm_rst_ps7_0_100M_0.xci
# IP: The module: 'sistema_pwm_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/sistema_pwmModule.srcs/sources_1/bd/sistema_pwm/ip/sistema_pwm_rst_ps7_0_100M_0/sistema_pwm_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwm_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/sistema_pwmModule.srcs/sources_1/bd/sistema_pwm/ip/sistema_pwm_rst_ps7_0_100M_0/sistema_pwm_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwm_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/sistema_pwmModule.srcs/sources_1/bd/sistema_pwm/ip/sistema_pwm_rst_ps7_0_100M_0/sistema_pwm_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwm_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/sistema_pwmModule.srcs/sources_1/bd/sistema_pwm/ip/sistema_pwm_rst_ps7_0_100M_0/sistema_pwm_rst_ps7_0_100M_0.xci
# IP: The module: 'sistema_pwm_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/sistema_pwmModule.srcs/sources_1/bd/sistema_pwm/ip/sistema_pwm_rst_ps7_0_100M_0/sistema_pwm_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwm_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/sistema_pwmModule.srcs/sources_1/bd/sistema_pwm/ip/sistema_pwm_rst_ps7_0_100M_0/sistema_pwm_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwm_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/sistema_pwmModule.srcs/sources_1/bd/sistema_pwm/ip/sistema_pwm_rst_ps7_0_100M_0/sistema_pwm_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwm_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
