# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sistema_pwm/sistema_pwm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_pwm || ORIG_REF_NAME==sistema_pwm} -quiet] -quiet

# IP: bd/sistema_pwm/ip/sistema_pwm_pwmModule_ip_0_0/sistema_pwm_pwmModule_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_pwm_pwmModule_ip_0_0 || ORIG_REF_NAME==sistema_pwm_pwmModule_ip_0_0} -quiet] -quiet

# IP: bd/sistema_pwm/ip/sistema_pwm_processing_system7_0_0/sistema_pwm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_pwm_processing_system7_0_0 || ORIG_REF_NAME==sistema_pwm_processing_system7_0_0} -quiet] -quiet

# IP: bd/sistema_pwm/ip/sistema_pwm_ps7_0_axi_periph_0/sistema_pwm_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_pwm_ps7_0_axi_periph_0 || ORIG_REF_NAME==sistema_pwm_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sistema_pwm/ip/sistema_pwm_rst_ps7_0_100M_0/sistema_pwm_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_pwm_rst_ps7_0_100M_0 || ORIG_REF_NAME==sistema_pwm_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/sistema_pwm/ip/sistema_pwm_auto_pc_0/sistema_pwm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_pwm_auto_pc_0 || ORIG_REF_NAME==sistema_pwm_auto_pc_0} -quiet] -quiet

# XDC: bd/sistema_pwm/sistema_pwm_ooc.xdc
