# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/Sistema_pwmModule_ip.srcs/sources_1/bd/sistema_pwmModule/ip/sistema_pwmModule_ila_0_0/sistema_pwmModule_ila_0_0.xci
# IP: The module: 'sistema_pwmModule_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/Sistema_pwmModule_ip.srcs/sources_1/bd/sistema_pwmModule/ip/sistema_pwmModule_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwmModule_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/Sistema_pwmModule_ip.srcs/sources_1/bd/sistema_pwmModule/ip/sistema_pwmModule_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwmModule_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/Sistema_pwmModule_ip.srcs/sources_1/bd/sistema_pwmModule/ip/sistema_pwmModule_ila_0_0/sistema_pwmModule_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwmModule_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/Sistema_pwmModule_ip.srcs/sources_1/bd/sistema_pwmModule/ip/sistema_pwmModule_ila_0_0/sistema_pwmModule_ila_0_0.xci
# IP: The module: 'sistema_pwmModule_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/Sistema_pwmModule_ip.srcs/sources_1/bd/sistema_pwmModule/ip/sistema_pwmModule_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwmModule_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/Sistema_pwmModule_ip.srcs/sources_1/bd/sistema_pwmModule/ip/sistema_pwmModule_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwmModule_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Disco1/RepositoriosGitHub/ProyectoMyS/Sistema_pwmModule_ip/Sintesis/Sistema_pwmModule_ip.srcs/sources_1/bd/sistema_pwmModule/ip/sistema_pwmModule_ila_0_0/sistema_pwmModule_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_pwmModule_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
